// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function CreateHost(arg1:store.Host):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function ListHosts():Promise<Array<store.Host>>;

export function UpdateHost(arg1:store.Host):Promise<void>;
