// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateHost(arg1) {
  return window['go']['main']['App']['CreateHost'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function ListHosts() {
  return window['go']['main']['App']['ListHosts']();
}

export function OpenTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenTerminal'](arg1, arg2, arg3);
}

export function SSHConnect(arg1) {
  return window['go']['main']['App']['SSHConnect'](arg1);
}

export function SSHDisconnect(arg1) {
  return window['go']['main']['App']['SSHDisconnect'](arg1);
}

export function TerminalClose(arg1) {
  return window['go']['main']['App']['TerminalClose'](arg1);
}

export function TerminalInput(arg1, arg2) {
  return window['go']['main']['App']['TerminalInput'](arg1, arg2);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function UpdateHost(arg1) {
  return window['go']['main']['App']['UpdateHost'](arg1);
}

export function SFTPOpen(arg1) {
  return window['go']['main']['App']['SFTPOpen'](arg1);
}

export function SFTPClose(arg1) {
  return window['go']['main']['App']['SFTPClose'](arg1);
}

export function SFTPListDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPListDir'](arg1, arg2);
}

export function SFTPGetwd(arg1) {
  return window['go']['main']['App']['SFTPGetwd'](arg1);
}

export function SFTPDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPDownload'](arg1, arg2, arg3);
}

export function SFTPUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPUpload'](arg1, arg2, arg3);
}

export function SFTPDelete(arg1, arg2) {
  return window['go']['main']['App']['SFTPDelete'](arg1, arg2);
}

export function SFTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPRename'](arg1, arg2, arg3);
}

export function SFTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['SFTPMkdir'](arg1, arg2);
}

export function GenerateSSHKey(arg1, arg2) {
  return window['go']['main']['App']['GenerateSSHKey'](arg1, arg2);
}

export function ImportSSHKey(arg1, arg2) {
  return window['go']['main']['App']['ImportSSHKey'](arg1, arg2);
}

export function ListSSHKeys() {
  return window['go']['main']['App']['ListSSHKeys']();
}

export function DeleteSSHKey(arg1) {
  return window['go']['main']['App']['DeleteSSHKey'](arg1);
}

export function GetPublicKey(arg1) {
  return window['go']['main']['App']['GetPublicKey'](arg1);
}

export function CreateHostWithPassword(arg1, arg2) {
  return window['go']['main']['App']['CreateHostWithPassword'](arg1, arg2);
}

export function CreateHostWithKey(arg1, arg2) {
  return window['go']['main']['App']['CreateHostWithKey'](arg1, arg2);
}

export function UpdateHostWithPassword(arg1, arg2) {
  return window['go']['main']['App']['UpdateHostWithPassword'](arg1, arg2);
}

export function UpdateHostWithKey(arg1, arg2) {
  return window['go']['main']['App']['UpdateHostWithKey'](arg1, arg2);
}
