// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ssh,store} from '../models';

export function CreateHost(arg1:store.Host):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function ListHosts():Promise<Array<store.Host>>;

export function OpenTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SSHConnect(arg1:string):Promise<string>;

export function SSHDisconnect(arg1:string):Promise<void>;

export function TerminalClose(arg1:string):Promise<void>;

export function TerminalInput(arg1:string,arg2:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function UpdateHost(arg1:store.Host):Promise<void>;

export function SFTPOpen(arg1:string):Promise<string>;
export function SFTPClose(arg1:string):Promise<void>;
export function SFTPListDir(arg1:string,arg2:string):Promise<Array<ssh.FileInfo>>;
export function SFTPGetwd(arg1:string):Promise<string>;
export function SFTPDownload(arg1:string,arg2:string,arg3:string):Promise<void>;
export function SFTPUpload(arg1:string,arg2:string,arg3:string):Promise<void>;
export function SFTPDelete(arg1:string,arg2:string):Promise<void>;
export function SFTPRename(arg1:string,arg2:string,arg3:string):Promise<void>;
export function SFTPMkdir(arg1:string,arg2:string):Promise<void>;

export function GenerateSSHKey(arg1:string,arg2:string):Promise<[string,string]>;
export function ImportSSHKey(arg1:string,arg2:string):Promise<string>;
export function ListSSHKeys():Promise<Array<store.KeyInfo>>;
export function DeleteSSHKey(arg1:string):Promise<void>;
export function GetPublicKey(arg1:string):Promise<string>;
