// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';
import {ssh} from '../models';

export function ClearSessionLogs():Promise<void>;

export function CreateHost(arg1:store.Host):Promise<void>;

export function CreateHostWithKey(arg1:store.Host,arg2:string):Promise<void>;

export function CreateHostWithPassword(arg1:store.Host,arg2:string):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function DeleteSSHKey(arg1:string):Promise<void>;

export function GenerateSSHKey(arg1:string,arg2:string):Promise<main.GeneratedKey>;

export function GetPublicKey(arg1:string):Promise<string>;

export function ImportSSHKey(arg1:string,arg2:string):Promise<string>;

export function ListHosts():Promise<Array<store.Host>>;

export function ListSSHKeys():Promise<Array<store.KeyInfo>>;

export function ListSessionLogs():Promise<Array<store.SessionLog>>;

export function OpenTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SFTPClose(arg1:string):Promise<void>;

export function SFTPDelete(arg1:string,arg2:string):Promise<void>;

export function SFTPDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPGetwd(arg1:string):Promise<string>;

export function SFTPListDir(arg1:string,arg2:string):Promise<Array<ssh.FileInfo>>;

export function SFTPMkdir(arg1:string,arg2:string):Promise<void>;

export function SFTPOpen(arg1:string):Promise<string>;

export function SFTPRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPUpload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SSHConnect(arg1:string):Promise<string>;

export function SSHDisconnect(arg1:string):Promise<void>;

export function TerminalClose(arg1:string):Promise<void>;

export function TerminalInput(arg1:string,arg2:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function UpdateHost(arg1:store.Host):Promise<void>;

export function UpdateHostWithKey(arg1:store.Host,arg2:string):Promise<void>;

export function UpdateHostWithPassword(arg1:store.Host,arg2:string):Promise<void>;
